force-app/main/default/objects/Vulnerable_Form__c/Vulnerable_Form__c.object-meta.xml
<CustomObject>
    <label>Vulnerable Form</label>
    <nameField>
        <displayFormat>F-{0000}</displayFormat>
        <label>Vulnerable Form Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vulnerable Forms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vulnerable_Form__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vulnerable Forms</relationshipLabel>
    <relationshipName>Vulnerable_Forms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
    public static void accountInsertion(List<Account> accList){
        List<Vulnerable_Form__c> vlnList = new List<Vulnerable_Form__c>();
        for(Account acc:[SELECT Id, Name FROM Account WHERE Id IN : Trigger.new]){
            Vulnerable_Form__c vln = new Vulnerable_Form__c(Customer_Name__c=acc.Id);
            	vlnList.add(vln);
        }
        insert vlnList;
    }
}